# Generated by Django 3.2.9 on 2023-11-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(db_index=True, max_length=250, verbose_name='Branch Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('branch_code', models.CharField(max_length=250, unique=True, verbose_name='Branch Code')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Bank Name')),
                ('bank_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='banksystem.branch', verbose_name='Bank Branch')),
            ],
        ),
    ]
