# Generated by Django 3.2.9 on 2023-11-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('branch_code', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
